#!/bin/bash
set -e

echo "Installing TinyXML2 version ${TINYXML2_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --depth 1 --branch "${TINYXML2_VERSION}" https://github.com/leethomason/tinyxml2.git "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir build && cd build
cmake .. \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_LIBDIR=lib
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "TinyXML2 installed successfully"
