#!/bin/bash
set -e

echo "Installing pybind11 version ${PYBIND11_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --depth 1 --branch "v${PYBIND11_VERSION}" https://github.com/pybind/pybind11.git "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir build
cd build
cmake .. -DPYBIND11_TEST=OFF -DCMAKE_BUILD_TYPE=Release
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "pybind11 installed successfully"
