#!/bin/bash
set -e

echo "Installing urdfdom_headers version ${URDFDOM_HEADERS_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --depth 1 --branch "${URDFDOM_HEADERS_VERSION}" https://github.com/ros/urdfdom_headers.git "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_POLICY_VERSION_MINIMUM=3.5
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "urdfdom_headers installed successfully"
