#!/bin/bash
set -e

echo "Installing console_bridge version ${CONSOLE_BRIDGE_VERSION}..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --depth 1 --branch "${CONSOLE_BRIDGE_VERSION}" https://github.com/ros/console_bridge.git "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir build && cd build
cmake .. \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "console_bridge installed successfully"
