#!/bin/bash
set -e

echo "Found the following Python versions:"
for PYBIN in /opt/python/*/bin; do
  PY_DIR=$(cut -d / -f 4 <<< "${PYBIN}")
  if [[ " ${PYBIN_SUPPORTED_VERSIONS} " == *" ${PY_DIR} "* ]]; then
     echo "${PY_DIR}"
  fi
done

echo "Setting up pip..."
for PYBIN in /opt/python/*/bin; do
  PY_DIR=$(cut -d / -f 4 <<< "${PYBIN}")
  if [[ " ${PYBIN_SUPPORTED_VERSIONS} " == *" ${PY_DIR} "* ]]; then
    "${PYBIN}/pip" install setuptools wheel --user
  fi
done
echo "pip set up successfully"
