#!/bin/bash
set -e

echo "Found the following Python versions:"
for PYBIN in /opt/python/*/bin; do
  PY_DIR=$(cut -d / -f 4 <<< "${PYBIN}")
  echo "${PY_DIR}"
done

echo "Setting up pip..."
for PYBIN in /opt/python/*/bin; do
  PY_DIR=$(cut -d / -f 4 <<< "${PYBIN}")
  "${PYBIN}/pip" install setuptools wheel --user
done
echo "pip set up successfully"
