name: Build wheels

on:
  workflow_call:
    inputs:
      libfranka-version:
        required: true
        type: string
      manylinux-version:
        required: true
        type: string

jobs:
  ensure-container:
    uses: ./.github/workflows/ensure_build_container.yml
    with:
      libfranka-version: ${{ inputs.libfranka-version }}
      manylinux-version: ${{ inputs.manylinux-version }}

  build_wheels:
    needs: ensure-container
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.ensure-container.outputs.image }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        run: ./docker/common/manylinux-build-wheels

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels___${{ inputs.libfranka-version }}___${{ inputs.manylinux-version }}
          path: output/libfranka_*_wheels.zip
