name: Build and test

on:
  workflow_call:
    inputs:
      libfranka-version:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential cmake git python3-dev libboost-all-dev liburdfdom-dev libfmt-dev libssl-dev libmysqlclient-dev libpq-dev

      - name: Install other dependencies
        run: |
          LIBFRANKA_VERSION=${{ inputs.libfranka-version }} ./docker/common/install-dependencies

      - name: Configure & make
        run: |
          mkdir build && cd build
          cmake ..
          make -j2

#      - name: Test
#        run: make test
