name: Build and test

on:
  workflow_call:
    inputs:
      libfranka-version:
        required: true
        type: string
      manylinux-version:
        required: true
        type: string

jobs:
  ensure-container:
    uses: ./.github/workflows/ensure_build_container.yml
    with:
      libfranka-version: ${{ inputs.libfranka-version }}
      manylinux-version: ${{ inputs.manylinux-version }}

  build_and_test:
    needs: ensure-container
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.ensure-container.outputs.image }}
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure & make
        run: |
          mkdir build && cd build
          cmake ..
          make -j2

#      - name: Test
#        run: make test
