name: Build and test

on:
  workflow_call:
    inputs:
      libfranka-version:
        required: true
        type: string
      manylinux-version:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/${{ inputs.manylinux-version }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          libfranka-version: ${{ inputs.libfranka-version }}
          manylinux-version: ${{ inputs.manylinux-version }}

      - name: Configure & make
        run: |
          mkdir build && cd build
          cmake ..
          make -j2

#      - name: Test
#        run: make test
