name: CI

on: [ push, pull_request ]

jobs:
  get-versions:
    uses: ./.github/workflows/get_libfranka_versions.yml

  build:
    needs: get-versions
    strategy:
      matrix:
        libfranka-version: ${{ fromJson(needs.get-versions.outputs.versions) }}
    uses: ./.github/workflows/build_and_test.yml
    with:
      libfranka-version: ${{ matrix.libfranka-version }}
      manylinux-version: manylinux_2_28_x86_64
