name: Documentation

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: dependencies
      env:
        dependency_packages: doxygen
      run: sudo apt-get update && sudo apt-get -y install ${dependency_packages}

    - name: build
      run: cd doc && VERSION=$(cat ../VERSION) doxygen ./Doxyfile

    - name: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
