name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        libfranka-version: [0.7.1, 0.8.0, 0.9.2, 0.10.0, 0.11.0, 0.12.1, 0.13.3, 0.14.2, 0.15.0]
    uses: ./.github/workflows/build_wheels.yml
    with:
      libfranka-version: ${{ matrix.libfranka-version }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write

    steps:
      - name: Prepare
        run: |
          mkdir -p artifacts

      - name: Get wheels
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          files: |
            artifacts/libfranka_*_wheels.zip

      - name: Unpack wheels
        run: |
          unzip artifacts/libfranka_0-15-0_wheels.zip

      - name: Publish python package
        uses: pypa/gh-action-pypi-publish@release/v1
